/**
 * Markdownレポート生成・クリップボード出力ユーティリティ
 * @module utils/reportExporter
 */

import { GameConfig } from '../types/config';
import { IntegratedAnalysisResult } from '../types/analysis';

/**
 * 統合分析結果からMarkdownレポート文字列を生成する
 * @param result 統合分析結果
 * @param gameConfig くじ種設定定数
 */
export function generateMarkdownReport(
  result: IntegratedAnalysisResult,
  gameConfig: GameConfig
): string {
  const { baseRound, latestMetrics, hotNumbers, goldNumbers, recoveryNumbers, coldNumbers, spanRanking, synergyPairs, digitDistributions } = result;

  const isLoto = gameConfig.category === 'loto';
  const formattedNumbers = baseRound.numbers.map((n) => String(n).padStart(2, '0')).join(', ');
  const bonusStr =
    isLoto && 'bonus' in baseRound && Array.isArray(baseRound.bonus) && baseRound.bonus.length > 0
      ? ` [ボーナス: ${baseRound.bonus.map((n) => String(n).padStart(2, '0')).join(', ')}]`
      : '';

  const zoneLabel = isLoto ? '黄金ゾーン' : '期待値ゾーン';
  const zoneStatus = latestMetrics.isGoldenZone
    ? `${zoneLabel}内 [${gameConfig.sumThresholds.expectedMin}〜${gameConfig.sumThresholds.expectedMax}]`
    : `${zoneLabel}外 [${gameConfig.sumThresholds.expectedMin}〜${gameConfig.sumThresholds.expectedMax}]`;

  const pullStr =
    latestMetrics.pullNumbers.length > 0
      ? `${latestMetrics.pullCount} 個 (${latestMetrics.pullNumbers.join(', ')})`
      : '0 個';

  const slideStr =
    latestMetrics.slideNumbers.length > 0
      ? `${latestMetrics.slideCount} 個 (${latestMetrics.slideNumbers.join(', ')})`
      : '0 個';

  let lines: string[] = [];

  lines.push(`# ロト＆ナンバーズ 統合構造解析レポート`);
  lines.push(`- **対象くじ種**: ${gameConfig.label}`);
  lines.push(`- **基準回号**: 第${baseRound.round}回 (${baseRound.date})`);
  lines.push(`- **集計対象**: 直近 ${result.targetRounds.length} 回`);
  lines.push(`- **基準回 当選数字**: ${formattedNumbers}${bonusStr}`);
  lines.push('');

  lines.push(`## 1. 構成解析指標 (第${baseRound.round}回)`);
  lines.push(`- **合計値**: ${latestMetrics.sum} (${zoneStatus})`);
  lines.push(`- **奇偶比**: 奇数 ${latestMetrics.oddCount} : 偶数 ${latestMetrics.evenCount}`);
  lines.push(`- **連番数**: ${latestMetrics.consecutiveCount} 組`);
  lines.push(`- **引っ張り**: ${pullStr}`);
  lines.push(`- **スライド**: ${slideStr}`);
  if (isLoto) {
    lines.push(`- **末尾被り**: ${latestMetrics.tailOverlapCount} 個`);
  } else if (latestMetrics.patternType) {
    lines.push(`- **出現パターン**: ${latestMetrics.patternType}`);
  }
  lines.push('');

  lines.push(`## 2. 出現頻度分類 (直近 ${result.targetRounds.length} 回)`);
  lines.push(`- **HOT (5回以上)**: ${hotNumbers.length > 0 ? hotNumbers.map((n) => String(n).padStart(2, '0')).join(', ') : 'なし'}`);
  lines.push(`- **GOLD (3〜4回)**: ${goldNumbers.length > 0 ? goldNumbers.map((n) => String(n).padStart(2, '0')).join(', ') : 'なし'}`);
  lines.push(`- **RECOVERY (2回)**: ${recoveryNumbers.length > 0 ? recoveryNumbers.map((n) => String(n).padStart(2, '0')).join(', ') : 'なし'}`);
  lines.push(`- **COLD (0〜1回)**: ${coldNumbers.length > 0 ? coldNumbers.map((n) => String(n).padStart(2, '0')).join(', ') : 'なし'}`);
  lines.push('');

  lines.push(`## 3. 未出現スパン (ハマり上位5数字)`);
  const topSpans = spanRanking.slice(0, 5);
  topSpans.forEach((item, index) => {
    lines.push(`${index + 1}. 数字 **${String(item.num).padStart(2, '0')}**: 現在 ${item.currentSpan} 回未出現 (期間内最大: ${item.maxSpan}回)`);
  });
  lines.push('');

  lines.push(`## 4. 共起ペア相性 (上位5ペア)`);
  const topPairs = synergyPairs.slice(0, 5);
  topPairs.forEach((item, index) => {
    const p1 = String(item.pair[0]).padStart(2, '0');
    const p2 = String(item.pair[1]).padStart(2, '0');
    lines.push(`${index + 1}. [${p1}, ${p2}]: **${item.count} 回** (${item.rate}%)`);
  });
  lines.push('');

  if (!isLoto && digitDistributions && digitDistributions.length > 0) {
    lines.push(`## 5. ナンバーズ 桁別最多出現数字`);
    digitDistributions.forEach((dist) => {
      let maxNum = 0;
      let maxCnt = -1;
      for (const [nStr, cnt] of Object.entries(dist.counts)) {
        if (cnt > maxCnt) {
          maxCnt = cnt;
          maxNum = Number(nStr);
        }
      }
      lines.push(`- **${dist.digitName}**: 最多出現 [${maxNum}] (${maxCnt}回)`);
    });
    lines.push('');
  }

  lines.push(`---`);
  lines.push(`*Generated by ロト＆ナンバーズ 統合構造解析・出目表可視化システム*`);

  return lines.join('\n');
}

/**
 * テキストをクリップボードにコピーする
 * @param text コピー対象テキスト
 */
export async function copyReportToClipboard(text: string): Promise<boolean> {
  try {
    if (navigator.clipboard && window.isSecureContext) {
      await navigator.clipboard.writeText(text);
      return true;
    } else {
      // フォールバック
      const textArea = document.createElement('textarea');
      textArea.value = text;
      textArea.style.position = 'fixed';
      textArea.style.left = '-999999px';
      textArea.style.top = '-999999px';
      document.body.appendChild(textArea);
      textArea.focus();
      textArea.select();
      const successful = document.execCommand('copy');
      document.body.removeChild(textArea);
      return successful;
    }
  } catch (err) {
    console.error('Failed to copy text to clipboard:', err);
    return false;
  }
}
